### ISSUE TITLE
make multiple users possible in one role statement

### ISSUE THREAD

**Issue by donvipre** [while-true-do/ansible-role-user#8]
### Type of Report

feature request

### Actual behaviour

play:
```yaml
- hosts: servers
  roles:
   - { role: while-true-do.user, wtd_user_name: user, wtd_user_comment: "user comment", wtd_user_groups: "wheel,adm", wtd_user_password_hash: hash, wtd_user_pub_keys: [ ~/.ssh/id_rsa.pub ] }
   - { role: while-true-do.user, wtd_user_name: user2, wtd_user_comment: "user2 comment", wtd_user_groups: "wheel,adm", wtd_user_password_hash: hash, wtd_user_pub_keys: [ ~/.ssh/id_rsa.pub ] }
```

### Expected behaviour

rename this role to **ansible-role-users**

play:
```yaml
- hosts: servers
  roles:
    - while-true-do.users
```
group_vars/servers.yml:
```yaml
wtd_users_userlist:
  - name: "user"
    shell: "/bin/false"
  - name: "user2"
    comment "test user 2"
  - name: "daemon"
    system: "yes"
```
